@startuml
skin rose
left to right direction

actor Player
actor Time

package Gameplay{
    usecase CallForNextImmigrant
    usecase AcceptPassport
    usecase RejectPassport
    usecase InspectPassport
    usecase TakeDecision  <<abstract>> 
    usecase EndDay
    usecase StartDay
    usecase StartWorkday
    usecase ShowNewspaper
    usecase EndWorkday
    usecase PassTime
    usecase CheckDailyRules
    usecase ManageDailySalary

    AcceptPassport -u-|> TakeDecision
    RejectPassport -u-|> TakeDecision
    
    actor System <<this is not ok :(>>
    
    System .u.> StartWorkday
    System .u.> EndDay
    System .u.> StartDay
    System .u.> ShowNewspaper
}

Player ..> CallForNextImmigrant
Player ..> InspectPassport
Player ..> TakeDecision
Player ..> ManageDailySalary
Player ..> CheckDailyRules

Time ..> EndWorkday
Time ..> PassTime


@enduml