@startuml
skin rose
left to right direction

actor Player
actor Time

package Gameplay{
    usecase CallForNextImmigrant
    usecase AcceptPassport
    usecase RejectPassport
    usecase InspectPassport <<abstract>> 
    usecase EndDay
    usecase StartDay
    usecase CheckDailyRules
    usecase ManageDailySalary

'    gestionar recursos

    AcceptPassport -u-|> InspectPassport
    RejectPassport -u-|> InspectPassport
}

Player ..> CallForNextImmigrant
Player ..> InspectPassport
Player ..> ManageDailySalary
Player ..> CheckDailyRules

Time ..> EndDay
Time ..> StartDay


@enduml